steps:
  # OBT-11: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/revenue-engine-repo/revenue-engine:$COMMIT_SHA', '.']

  # OBT-18: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/revenue-engine-repo/revenue-engine:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/revenue-engine-repo/revenue-engine:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY